name: papela
description: "A modern web-based rental management system for Papela Event Rentals"
publish_to: "none"
version: 1.0.0+1
environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  firebase_storage: ^13.0.0
  provider: ^6.1.5+1
  go_router: ^16.2.0
  google_fonts: ^6.3.0
  intl: ^0.20.2
  flutter_dotenv: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/